# .swiftlint.yml
disabled_rules:
    - private_over_fileprivate
    - multiple_closures_with_trailing_closure

opt_in_rules:
    - empty_count
    - empty_string
    - array_init
    - redundant_nil_coalescing
    - trailing_closure

analyzer_rules:
    - unused_import
    - unused_declaration

identifier_name:
    excluded: ["rx", "vm", "id", "URL", "GlobalAPIKey"]
    allowed_symbols: "_"
    min_length:
        warning: 3
        error: 2

line_length:
    error: 100

function_body_length:
    error: 50

type_body_length:
    error: 300

file_length:
    warning: 200
    error: 400

trailing_closure:
    severity: warning

force_unwrapping:
    severity: error

force_cast:
    severity: error

excluded:
    - Libraries
    - ExchangeCalculatorTests
    - daeun/ExchangeCalculatorUITests
    - daeun/ExchangeCalulatorTests

reporter: "xcode"
