# .swiftlint.yml

disabled_rules:
    - private_over_fileprivate
    - trailing_whitespace
    - multiple_closures_with_trailing_closure
    - force_cast

### used opt
opt_in_rules:
    - empty_count
    - empty_string
    - array_init # Array<T>() -> []
    - redundant_nil_coalescing #?? nil
    - implicitly_unwrapped_optional # String!
    - trailing_closure
    - force_cast
    - force_unwrapping
### analyzer_rules
analyzer_rules:
    - unused_import
    - unused_declaration
### naming
identifier_name:
    excluded: ["rx", "vm", "id", "URL", "GlobalAPIKey"]
    allowed_symbols: "_"
    min_length:
        warning: 3
        error: 2

### max line, function, type
line_length:
    error: 100
    
function_body_length:
    error: 50
  
type_body_length:
    error: 300
    
file_length:
    warning: 200
    error: 400

### Code Sytle
trailing_closure:
    severity: warning

### Force Unwrapping & Casting
force_unwrapping:
    severity: error

excluded:
    - Pods
    - ExchangeCalulator/App/AppDelegate.swift
    - Libraries
    - ExchangeCalulator/Network/DTO/ExchangeRateReponseDTO.swift
    - ExchangeCalulatorTests/ExchangeCalulatorServiceTests.swift

custom_rules:
  prohibit_lower_snake_case:
    name: "Prohibit Lower Snake Case"
    regex: "[a-z]+_[a-z]+"
    message: "Identifiers should not be written in lower snake case."
    severity: error

reporter: "xcode"
